# Generated by Django 5.2.3 on 2026-01-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客戶姓名')),
                ('items', models.TextField(verbose_name='訂單內容')),
                ('total_price', models.IntegerField(verbose_name='總金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下單時間')),
            ],
        ),
    ]
